<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Monetrix_Board_Viewer_Simple.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Monetrix_Board_Viewer_Simple.ico" />
  </ItemGroup>

</Project>