using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;

public static class ArduinoImageBoxConverter
{
    // ============================================================
    // BOX
    // ============================================================

    public sealed class ImageBox
    {
        public byte X { get; }
        public byte Y { get; }
        public byte Width { get; }
        public byte Height { get; }
        public byte ColorIndex { get; }

        public ImageBox(
            int x,
            int y,
            int width,
            int height,
            int colorIndex)
        {
            if (x < 0 || x > 255)
                throw new ArgumentOutOfRangeException(nameof(x));

            if (y < 0 || y > 255)
                throw new ArgumentOutOfRangeException(nameof(y));

            if (width < 1 || width > 255)
                throw new ArgumentOutOfRangeException(nameof(width));

            if (height < 1 || height > 255)
                throw new ArgumentOutOfRangeException(nameof(height));

            if (colorIndex < 0 || colorIndex > 255)
                throw new ArgumentOutOfRangeException(nameof(colorIndex));

            X = (byte)x;
            Y = (byte)y;
            Width = (byte)width;
            Height = (byte)height;
            ColorIndex = (byte)colorIndex;
        }
    }


    // ============================================================
    // RESULT
    // ============================================================

    public sealed class BoxImage
    {
        public int Width { get; }
        public int Height { get; }

        public ArduinoImageConverter.ColorDepth ColorDepth { get; }

        public ImageBox[] Boxes { get; }

        public Color[] Palette { get; }

        public int BoxCount => Boxes.Length;

        public int ColorsCount => Palette.Length;

        public BoxImage(
            int width,
            int height,
            ArduinoImageConverter.ColorDepth colorDepth,
            ImageBox[] boxes,
            Color[] palette)
        {
            Width = width;
            Height = height;
            ColorDepth = colorDepth;
            Boxes = boxes;
            Palette = palette;
        }


        // ========================================================
        // ARDUINO CODE
        // ========================================================

        public string ToArduinoCode(
            string name,
            bool useColor565 = false)
        {
            if (string.IsNullOrWhiteSpace(name))
                throw new ArgumentException(
                    "Name cannot be empty.",
                    nameof(name));

            string identifier =
                MakeIdentifier(name);

            string macroName =
                identifier.ToUpperInvariant();

            var sb = new StringBuilder();

            sb.AppendLine("// ============================================================");
            sb.AppendLine("// Generated by ArduinoImageBoxConverter");
            sb.AppendLine("// ============================================================");
            sb.AppendLine();

            sb.AppendLine("#include <Arduino.h>");
            sb.AppendLine();

            // ----------------------------------------------------
            // DEFINES
            // ----------------------------------------------------

            sb.AppendLine(
                $"#define {macroName}_WIDTH       {Width}");

            sb.AppendLine(
                $"#define {macroName}_HEIGHT      {Height}");

            sb.AppendLine(
                $"#define {macroName}_BPP         {(int)ColorDepth}");

            sb.AppendLine(
                $"#define {macroName}_COLORS      {ColorsCount}");

            sb.AppendLine(
                $"#define {macroName}_BOX_COUNT   {BoxCount}");

            sb.AppendLine();

            // ----------------------------------------------------
            // BOX STRUCT
            // ----------------------------------------------------

            sb.AppendLine(
                $"struct {identifier}Box");

            sb.AppendLine("{");

            sb.AppendLine("    uint8_t x;");
            sb.AppendLine("    uint8_t y;");
            sb.AppendLine("    uint8_t width;");
            sb.AppendLine("    uint8_t height;");
            sb.AppendLine("    uint8_t color;");

            sb.AppendLine("};");
            sb.AppendLine();

            // ----------------------------------------------------
            // BOX DATA
            // ----------------------------------------------------

            sb.AppendLine(
                $"const {identifier}Box " +
                $"{identifier}Boxes[] PROGMEM =");

            sb.AppendLine("{");

            for (int i = 0; i < Boxes.Length; i++)
            {
                ImageBox box = Boxes[i];

                sb.AppendLine(
                    $"    {{ {box.X}, {box.Y}, " +
                    $"{box.Width}, {box.Height}, " +
                    $"{box.ColorIndex} }}" +
                    (i < Boxes.Length - 1 ? "," : ""));
            }

            sb.AppendLine("};");
            sb.AppendLine();

            // ----------------------------------------------------
            // PALETTE
            // ----------------------------------------------------

            if (useColor565)
            {
                sb.AppendLine(
                    $"const uint16_t {identifier}Palette" +
                    $"[{ColorsCount}] PROGMEM =");

                sb.AppendLine("{");

                for (int i = 0; i < Palette.Length; i++)
                {
                    ushort rgb565 =
                        ToRgb565(Palette[i]);

                    sb.Append(
                        $"    0x{rgb565:X4}");

                    if (i < Palette.Length - 1)
                        sb.Append(",");

                    sb.AppendLine();
                }

                sb.AppendLine("};");
            }
            else
            {
                sb.AppendLine(
                    $"const uint8_t {identifier}Palette" +
                    $"[{ColorsCount}][3] PROGMEM =");

                sb.AppendLine("{");

                for (int i = 0; i < Palette.Length; i++)
                {
                    Color c = Palette[i];

                    sb.AppendLine(
                        $"    {{ {c.R}, {c.G}, {c.B} }}" +
                        (i < Palette.Length - 1 ? "," : ""));
                }

                sb.AppendLine("};");
            }

            sb.AppendLine();

            // ----------------------------------------------------
            // DRAW IMAGE
            // ----------------------------------------------------

            AppendDrawImageFunction(
                sb,
                identifier,
                macroName,
                useColor565);

            return sb.ToString();
        }


        // ========================================================
        // SAVE HEADER
        // ========================================================

        public void SaveArduinoHeader(
            string filename,
            string name,
            bool useColor565 = false)
        {
            System.IO.File.WriteAllText(
                filename,
                ToArduinoCode(
                    name,
                    useColor565));
        }
    }


    // ============================================================
    // CONVERT
    // ============================================================

    public static BoxImage Convert(
        ArduinoImageConverter.IndexedImage image)
    {
        if (image == null)
            throw new ArgumentNullException(nameof(image));

        if (image.Width < 1 || image.Width > 256)
            throw new ArgumentOutOfRangeException(
                nameof(image.Width),
                "Image width must be between 1 and 256.");

        if (image.Height < 1 || image.Height > 256)
            throw new ArgumentOutOfRangeException(
                nameof(image.Height),
                "Image height must be between 1 and 256.");

        byte[] indexes =
            UnpackIndexes(
                image.Data,
                image.Width,
                image.Height,
                image.ColorDepth);

        List<ImageBox> boxes =
            BuildBoxes(
                indexes,
                image.Width,
                image.Height);

        return new BoxImage(
            image.Width,
            image.Height,
            image.ColorDepth,
            boxes.ToArray(),
            image.Palette);
    }


    // ============================================================
    // BUILD BOXES
    //
    // LAYER RULE:
    //
    // Layer 0:
    //     Always fills the complete image.
    //
    // Layer N:
    //     Can overwrite:
    //         - itself
    //         - any later layer
    //
    //     Cannot overwrite:
    //         - any earlier layer
    //
    // Example:
    //
    //     Layer 0 = background
    //     Layer 1 = large shape
    //     Layer 2 = text
    //
    // Layer 1 may initially paint over Layer 2.
    // Layer 2 is then painted afterward.
    //
    // ============================================================

    private static List<ImageBox> BuildBoxes(
        byte[] pixels,
        int width,
        int height)
    {
        var boxes =
            new List<ImageBox>();

        int pixelCount =
            width * height;

        if (pixelCount == 0)
            return boxes;

        // ========================================================
        // COUNT COLORS
        // ========================================================

        int[] colorCounts =
            new int[256];

        for (int i = 0;
             i < pixelCount;
             i++)
        {
            colorCounts[pixels[i]]++;
        }

        // ========================================================
        // SORT COLORS
        //
        // Most common -> least common
        // ========================================================

        byte[] colors =
            Enumerable
                .Range(0, 256)
                .Where(c => colorCounts[c] > 0)
                .OrderByDescending(c => colorCounts[c])
                .Select(c => (byte)c)
                .ToArray();

        if (colors.Length == 0)
            return boxes;

        // ========================================================
        // COLOR -> LAYER
        //
        // Example:
        //
        // color 5  -> layer 0
        // color 12 -> layer 1
        // color 2  -> layer 2
        //
        // ========================================================

        int[] colorLayer =
            new int[256];

        Array.Fill(
            colorLayer,
            -1);

        for (int layer = 0;
             layer < colors.Length;
             layer++)
        {
            colorLayer[colors[layer]] =
                layer;
        }

        // ========================================================
        // LAYER 0
        //
        // DOMINANT COLOR ALWAYS FILLS
        // THE ENTIRE IMAGE.
        //
        // This box is deliberately unconditional.
        // ========================================================

        boxes.Add(
            new ImageBox(
                0,
                0,
                width,
                height,
                colors[0]));

        if (colors.Length == 1)
            return boxes;

        // ========================================================
        // USED
        //
        // Prevents boxes from the SAME layer
        // from overlapping each other.
        //
        // It does NOT protect earlier layers.
        //
        // Generation counter means we don't need to clear
        // the array for every layer.
        // ========================================================

        int[] used =
            new int[pixelCount];

        int generation = 0;

        // ========================================================
        // PROCESS LAYERS
        // ========================================================

        for (int layer = 1;
             layer < colors.Length;
             layer++)
        {
            byte color =
                colors[layer];

            generation++;

            // ====================================================
            // TOP -> BOTTOM
            // LEFT -> RIGHT
            // ====================================================

            for (int y = 0;
                 y < height;
                 y++)
            {
                for (int x = 0;
                     x < width;
                     x++)
                {
                    int startIndex =
                        y * width + x;

                    // ------------------------------------------------
                    // Already covered by another box
                    // from this layer.
                    // ------------------------------------------------

                    if (used[startIndex] == generation)
                        continue;

                    // ------------------------------------------------
                    // We only START a box on a pixel whose FINAL
                    // color belongs to this layer.
                    // ------------------------------------------------

                    if (pixels[startIndex] != color)
                        continue;

                    // ====================================================
                    // FIND MAXIMUM WIDTH
                    //
                    // Current layer may cross:
                    //
                    //     current layer
                    //     future layers
                    //
                    // But NOT:
                    //
                    //     earlier layers
                    // ====================================================

                    int maxWidth = 0;

                    while (x + maxWidth < width)
                    {
                        int index =
                            startIndex + maxWidth;

                        // Already consumed by this layer.
                        if (used[index] == generation)
                            break;

                        // Earlier layer = protected.
                        if (colorLayer[pixels[index]] < layer)
                            break;

                        maxWidth++;
                    }

                    if (maxWidth == 0)
                        continue;

                    // ====================================================
                    // FIND BEST RECTANGLE
                    // ====================================================

                    int bestWidth = 1;
                    int bestHeight = 1;

                    int currentWidth =
                        maxWidth;

                    for (int h = 1;
                         y + h <= height;
                         h++)
                    {
                        int rowStart =
                            (y + h - 1) * width + x;

                        int rowWidth = 0;

                        while (rowWidth < currentWidth)
                        {
                            int index =
                                rowStart + rowWidth;

                            // Already consumed by this layer.
                            if (used[index] == generation)
                                break;

                            // Earlier layer = protected.
                            if (colorLayer[pixels[index]] < layer)
                                break;

                            rowWidth++;
                        }

                        if (rowWidth == 0)
                            break;

                        // Rectangle width can only shrink
                        // as we go downward.
                        currentWidth =
                            rowWidth;

                        int area =
                            currentWidth * h;

                        int bestArea =
                            bestWidth * bestHeight;

                        if (area > bestArea)
                        {
                            bestWidth =
                                currentWidth;

                            bestHeight =
                                h;
                        }
                    }

                    // ====================================================
                    // CREATE BOX
                    // ====================================================

                    boxes.Add(
                        new ImageBox(
                            x,
                            y,
                            bestWidth,
                            bestHeight,
                            color));

                    // ====================================================
                    // MARK BOX USED
                    //
                    // IMPORTANT:
                    //
                    // These pixels are only marked as used for
                    // THIS layer.
                    //
                    // A later layer is still allowed to overwrite
                    // them.
                    // ====================================================

                    for (int yy = y;
                         yy < y + bestHeight;
                         yy++)
                    {
                        int offset =
                            yy * width + x;

                        for (int xx = 0;
                             xx < bestWidth;
                             xx++)
                        {
                            used[offset + xx] =
                                generation;
                        }
                    }
                }
            }
        }

        return boxes;
    }


    // ============================================================
    // UNPACK INDEXES
    // ============================================================

    private static byte[] UnpackIndexes(
        byte[] data,
        int width,
        int height,
        ArduinoImageConverter.ColorDepth colorDepth)
    {
        int bits =
            (int)colorDepth;

        int pixelsPerByte =
            8 / bits;

        int mask =
            (1 << bits) - 1;

        byte[] indexes =
            new byte[width * height];

        for (int i = 0;
             i < indexes.Length;
             i++)
        {
            int byteIndex =
                i / pixelsPerByte;

            int position =
                i % pixelsPerByte;

            int shift =
                8 - bits * (position + 1);

            indexes[i] =
                (byte)(
                    (data[byteIndex] >> shift) &
                    mask);
        }

        return indexes;
    }


    // ============================================================
    // DRAW IMAGE FUNCTION
    // ============================================================

    private static void AppendDrawImageFunction(
        StringBuilder sb,
        string identifier,
        string macroName,
        bool useColor565)
    {
        sb.AppendLine(
            $"static inline void {identifier}DrawImage(");

        sb.AppendLine(
            "    int16_t offsetX,");

        sb.AppendLine(
            "    int16_t offsetY,");

        sb.AppendLine(
            "    int16_t scaleX = 1,");

        sb.AppendLine(
            "    int16_t scaleY = 1)");

        sb.AppendLine("{");

        sb.AppendLine(
            $"    for (uint16_t i = 0; " +
            $"i < {macroName}_BOX_COUNT; i++)");

        sb.AppendLine("    {");

        sb.AppendLine(
            $"        {identifier}Box box;");

        sb.AppendLine();

        sb.AppendLine(
            $"        memcpy_P(" +
            $"&box, " +
            $"&{identifier}Boxes[i], " +
            $"sizeof(box));");

        sb.AppendLine();

        // ========================================================
        // COLOR
        // ========================================================

        if (useColor565)
        {
            sb.AppendLine(
                $"        uint16_t color = " +
                $"pgm_read_word(" +
                $"&{identifier}Palette[box.color]);");
        }
        else
        {
            sb.AppendLine(
                $"        uint8_t r = pgm_read_byte(" +
                $"&{identifier}Palette[box.color][0]);");

            sb.AppendLine(
                $"        uint8_t g = pgm_read_byte(" +
                $"&{identifier}Palette[box.color][1]);");

            sb.AppendLine(
                $"        uint8_t b = pgm_read_byte(" +
                $"&{identifier}Palette[box.color][2]);");

            sb.AppendLine();

            sb.AppendLine(
                "        uint16_t color = (uint16_t)(");

            sb.AppendLine(
                "            ((r & 0xF8) << 8) |");

            sb.AppendLine(
                "            ((g & 0xFC) << 3) |");

            sb.AppendLine(
                "            (b >> 3));");
        }

        sb.AppendLine();

        // ========================================================
        // DRAW BOX
        // ========================================================

        sb.AppendLine(
            "        tft.fillRect(");

        sb.AppendLine(
            "            offsetX + box.x * scaleX,");

        sb.AppendLine(
            "            offsetY + box.y * scaleY,");

        sb.AppendLine(
            "            box.width * scaleX,");

        sb.AppendLine(
            "            box.height * scaleY,");

        sb.AppendLine(
            "            color);");

        sb.AppendLine("    }");

        sb.AppendLine("}");

        sb.AppendLine();
    }


    // ============================================================
    // RGB888 -> RGB565
    // ============================================================

    private static ushort ToRgb565(
        Color color)
    {
        return (ushort)(
            ((color.R & 0xF8) << 8) |
            ((color.G & 0xFC) << 3) |
            (color.B >> 3));
    }


    // ============================================================
    // IDENTIFIER
    // ============================================================

    private static string MakeIdentifier(
        string name)
    {
        var sb =
            new StringBuilder();

        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) ||
                c == '_')
            {
                sb.Append(c);
            }
            else
            {
                sb.Append('_');
            }
        }

        if (sb.Length == 0)
            sb.Append("image");

        if (char.IsDigit(sb[0]))
            sb.Insert(0, '_');

        return sb.ToString();
    }
}