using Image2Cpp.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Drawing.Imaging.Effects;
using System.Text;
using System.Runtime.InteropServices;

public static class ArduinoImageConverter
{
    // ============================================================
    // COLOR DEPTH
    // ============================================================

    public enum ColorDepth
    {
        Bpp1 = 1,   // 2 colors
        Bpp2 = 2,   // 4 colors
        Bpp4 = 4,   // 16 colors
        Bpp8 = 8    // 256 colors
    }


    // ============================================================
    // RESULT
    // ============================================================

    public sealed class IndexedImage
    {
        public int Width { get; }
        public int Height { get; }
        public ColorDepth ColorDepth { get; }

        // Packed pixel indexes
        public byte[] Data { get; }

        // RGB palette
        public Color[] Palette { get; }

        // Transparent palette index (-1 = none)
        public int TransparentIndex { get; }

        public int ColorsCount => Palette.Length;

        public int BitsPerPixel => (int)ColorDepth;

        public IndexedImage(
            int width,
            int height,
            ColorDepth colorDepth,
            byte[] data,
            Color[] palette,
            int transparentIndex = -1)
        {
            Width = width;
            Height = height;
            ColorDepth = colorDepth;
            Data = data;
            Palette = palette;
            TransparentIndex = transparentIndex;
        }


        // ========================================================
        // ARDUINO CODE GENERATION
        // ========================================================

        public string ToArduinoCode(DataModel data)
        {
            if (string.IsNullOrWhiteSpace(data.Output.Name))
                throw new ArgumentException("Name cannot be empty.", nameof(data.Output.Name));

            string identifier = MakeIdentifier(data.Output.Name);
            string macroName = identifier.ToUpperInvariant();

            var sb = new StringBuilder();

            sb.AppendLine("// ============================================================");
            sb.AppendLine($"// Generated by ArduinoImageConverter - {macroName}");
            sb.AppendLine("// ============================================================");
            sb.AppendLine();

            sb.AppendLine($"#define {macroName}_WIDTH       {Width}");
            sb.AppendLine($"#define {macroName}_HEIGHT      {Height}");
            sb.AppendLine($"#define {macroName}_BPP         {BitsPerPixel}");
            sb.AppendLine($"#define {macroName}_COLORS      {ColorsCount}");
            sb.AppendLine($"#define {macroName}_DATA_SIZE   {Data.Length}");
            sb.AppendLine();

            // ----------------------------------------------------
            // PIXEL DATA
            // ----------------------------------------------------

            sb.AppendLine($"const uint8_t {identifier}[] PROGMEM =");
            sb.AppendLine("{");

            AppendByteArray(sb, Data);

            sb.AppendLine("};");
            sb.AppendLine();

            // ----------------------------------------------------
            // PALETTE
            // ----------------------------------------------------

            if (data.Output.UseColor565)
            {
                sb.AppendLine(
                    $"const uint16_t {identifier}Palette[{ColorsCount}] PROGMEM =");
                sb.AppendLine("{");

                for (int i = 0; i < Palette.Length; i++)
                {
                    ushort rgb565 = ToRgb565(Palette[i]);

                    sb.Append($"    0x{rgb565:X4}");

                    if (i < Palette.Length - 1)
                        sb.Append(",");

                    sb.AppendLine();
                }

                sb.AppendLine("};");
            }
            else
            {
                sb.AppendLine(
                    $"const uint8_t {identifier}Palette[{ColorsCount}][3] PROGMEM =");
                sb.AppendLine("{");

                for (int i = 0; i < Palette.Length; i++)
                {
                    Color c = Palette[i];

                    sb.AppendLine(
                        $"    {{ {c.R}, {c.G}, {c.B} }}" +
                        (i < Palette.Length - 1 ? "," : ""));
                }

                sb.AppendLine("};");
            }

            sb.AppendLine();

            // ----------------------------------------------------
            // TRANSPARENCY
            // ----------------------------------------------------
            bool hasTransparency = TransparentIndex >= 0 && this.TransparentIndex < Palette.Length;
            if (hasTransparency)
            {
                sb.AppendLine($"#define {macroName}_TRANSPARENT_INDEX   {this.TransparentIndex}");
                sb.AppendLine();
            }

            // ----------------------------------------------------
            // GET PIXEL
            // ----------------------------------------------------

            if (data.Output.IncludeRenderFunction)
            {
                AppendGetPixelFunction(
                    sb,
                    identifier,
                    macroName,
                    data.Output.UseColor565,
                    hasTransparency);
            }

            return sb.ToString();
        }

        public Bitmap ToBitmap()
        {
            return ToBitmap(preview: false);
        }

        public Bitmap ToBitmap(bool preview = false)
        {
            int bitsPerPixel = BitsPerPixel;
            int pixelsPerByte = 8 / bitsPerPixel;
            int mask = (1 << bitsPerPixel) - 1;

            bool hasTransparency = TransparentIndex >= 0;

            // Build foreground buffer as 32bpp ARGB (non-premultiplied) in memory
            int fgStride = Width * 4;
            byte[] fgBuffer = new byte[fgStride * Height];

            for (int i = 0; i < Width * Height; i++)
            {
                int byteIndex = i / pixelsPerByte;
                int position = i % pixelsPerByte;
                int shift = 8 - bitsPerPixel * (position + 1);

                int paletteIndex = (Data[byteIndex] >> shift) & mask;

                int x = i % Width;
                int y = i / Width;

                int off = y * fgStride + x * 4;

                if (hasTransparency && paletteIndex == TransparentIndex)
                {
                    // Fully transparent pixel: all bytes zero
                    fgBuffer[off + 0] = 0;
                    fgBuffer[off + 1] = 0;
                    fgBuffer[off + 2] = 0;
                    fgBuffer[off + 3] = 0;
                }
                else
                {
                    Color color = Palette[paletteIndex];
                    fgBuffer[off + 0] = color.B;
                    fgBuffer[off + 1] = color.G;
                    fgBuffer[off + 2] = color.R;
                    fgBuffer[off + 3] = 255;
                }
            }

            // If non-preview, return a 32bpp bitmap constructed from fgBuffer
            if (!preview)
            {
                var fg = new Bitmap(Width, Height, PixelFormat.Format32bppArgb);
                var bd = fg.LockBits(new Rectangle(0, 0, Width, Height), ImageLockMode.WriteOnly, PixelFormat.Format32bppArgb);
                try
                {
                    Marshal.Copy(fgBuffer, 0, bd.Scan0, fgBuffer.Length);
                }
                finally
                {
                    fg.UnlockBits(bd);
                }

                return fg;
            }

            // Preview: build 24bpp checkerboard then copy opaque pixels from fgBuffer
            var previewBmp = new Bitmap(Width, Height, PixelFormat.Format24bppRgb);

            int cell = 8;
            Color c1 = Color.FromArgb(220, 220, 220);
            Color c2 = Color.FromArgb(180, 180, 180);

            int pbStride = ((Width * 3 + 3) / 4) * 4;
            byte[] pbBuffer = new byte[pbStride * Height];

            // Fill checkerboard
            for (int y = 0; y < Height; y++)
            {
                for (int x = 0; x < Width; x++)
                {
                    bool odd = ((x / cell) + (y / cell)) % 2 == 1;
                    Color baseColor = odd ? c1 : c2;

                    int off = y * pbStride + x * 3;
                    pbBuffer[off + 0] = baseColor.B;
                    pbBuffer[off + 1] = baseColor.G;
                    pbBuffer[off + 2] = baseColor.R;
                }
            }

            // Copy opaque pixels from fgBuffer to pbBuffer
            for (int y = 0; y < Height; y++)
            {
                for (int x = 0; x < Width; x++)
                {
                    int i = y * Width + x;
                    int foff = y * fgStride + x * 4;

                    byte a = fgBuffer[foff + 3];
                    if (a == 0)
                        continue;

                    int pbOff = y * pbStride + x * 3;
                    pbBuffer[pbOff + 0] = fgBuffer[foff + 0];
                    pbBuffer[pbOff + 1] = fgBuffer[foff + 1];
                    pbBuffer[pbOff + 2] = fgBuffer[foff + 2];
                }
            }

            var bd2 = previewBmp.LockBits(new Rectangle(0, 0, Width, Height), ImageLockMode.WriteOnly, PixelFormat.Format24bppRgb);
            try
            {
                Marshal.Copy(pbBuffer, 0, bd2.Scan0, pbBuffer.Length);
            }
            finally
            {
                previewBmp.UnlockBits(bd2);
            }

            return previewBmp;
        }

    }


    // ============================================================
    // PUBLIC CONVERSION FUNCTION
    // ============================================================

    public static IndexedImage Convert(DataModel data)
    {
        if (data == null)
            throw new ArgumentNullException(nameof(data));
        if (data.Image == null)
            throw new ArgumentNullException(nameof(data.Image));

        if (data.Input.Resize.Width <= 0)
            throw new ArgumentOutOfRangeException(nameof(data.Input.Resize.Width));


        if (data.Input.Resize.Height <= 0)
            throw new ArgumentOutOfRangeException(nameof(data.Input.Resize.Height));

        int colorsCount = GetColorsCount(data.Output.Palette);

        using Bitmap resized = GetImage(data);    

        // Read pixels including alpha channel so transparent source pixels are detected
        Color[] pixels = GetPixels(resized);

        // --------------------------------------------------
        // Handle transparent color + tolerance (Euclidean) and source alpha
        // - Support TransparentFromTopLeft: take effective transparent color from top-left pixel
        // - Treat any pixel with alpha < 255 as transparent (mask)
        // --------------------------------------------------
        Color effectiveTransparentColor = data.Output.TransparentColor;
        if (data.Output.TransparentFromTopLeft && effectiveTransparentColor.IsEmpty && pixels.Length > 0)
        {
            // top-left pixel after resize/crop
            effectiveTransparentColor = pixels[0];
        }

        // Detect any source alpha transparency
        bool hasAlphaTransparency = false;
        for (int i = 0; i < pixels.Length; i++)
        {
            if (pixels[i].A < 255)
            {
                hasAlphaTransparency = true;
                break;
            }
        }

        bool hasTransparentColor = !effectiveTransparentColor.IsEmpty || hasAlphaTransparency;

        bool[] transparentMask = new bool[pixels.Length];

        // First mark pixels that are transparent due to source alpha
        if (hasAlphaTransparency)
        {
            for (int i = 0; i < pixels.Length; i++)
            {
                transparentMask[i] = pixels[i].A < 190;
            }
        }

        // Then also mark pixels that match the transparent color within tolerance
        if (!effectiveTransparentColor.IsEmpty)
        {
            int tol = Math.Max(0, data.Output.TransparentTolerance);
            long tol2 = (long)tol * (long)tol;

            Color tc = effectiveTransparentColor;

            for (int i = 0; i < pixels.Length; i++)
            {
                int dr = pixels[i].R - tc.R;
                int dg = pixels[i].G - tc.G;
                int db = pixels[i].B - tc.B;

                long dist2 = (long)dr * dr + (long)dg * dg + (long)db * db;

                if (dist2 <= tol2)
                    transparentMask[i] = true;
            }
        }

        // Build palette excluding transparent pixels when appropriate
        Color[] palette;

        int maxPaletteSlots = GetColorsCount(data.Output.Palette);
        int maxColorsAllowed = (int)Math.Min(maxPaletteSlots, data.Input.MaxColors);

        if (hasTransparentColor)
        {
            var list = new List<Color>(pixels.Length);

            for (int i = 0; i < pixels.Length; i++)
            {
                if (!transparentMask[i])
                    list.Add(pixels[i]);
            }

            if (list.Count == 0)
            {
                // all pixels transparent: start with an empty palette
                palette = new Color[0];
            }
            else
            {
                // reserve one slot for the transparent color
                int paletteSlotsForColors = Math.Max(0, maxColorsAllowed - 1);
                if (paletteSlotsForColors <= 0)
                {
                    // no room for colors except the transparent one
                    palette = new Color[0];
                }
                else
                {
                    palette = BuildPalette(
                        list.ToArray(),
                        paletteSlotsForColors);
                }
            }
        }
        else
        {
            palette = BuildPalette(
                pixels,
                maxColorsAllowed);
        }

        // Build final palette list: if transparency requested, put transparent color at palette[0]
        var palList = new List<Color>();
        int computedTransparentIndex = -1;

        if (hasTransparentColor)
        {
            // Determine representative RGB for transparent pixels
            Color tc = effectiveTransparentColor;
            if (tc.IsEmpty && hasAlphaTransparency)
            {
                long sr = 0, sg = 0, sb = 0;
                int scount = 0;
                for (int i = 0; i < pixels.Length; i++)
                {
                    if (transparentMask[i])
                    {
                        sr += pixels[i].R;
                        sg += pixels[i].G;
                        sb += pixels[i].B;
                        scount++;
                    }
                }

                if (scount > 0)
                {
                    tc = Color.FromArgb((int)(sr / scount), (int)(sg / scount), (int)(sb / scount));
                }
                else if (pixels.Length > 0)
                {
                    tc = pixels[0];
                }
            }

            // Ensure transparent color occupies palette index 0
            palList.Add(Color.FromArgb(tc.R, tc.G, tc.B));
            computedTransparentIndex = 0;

            // Append computed palette colors (from non-transparent pixels) up to remaining slots
            int remainingSlots = Math.Max(0, maxPaletteSlots - 1);
            for (int i = 0; i < palette.Length && palList.Count < 1 + remainingSlots; i++)
            {
                palList.Add(palette[i]);
            }

            // Append include colors if space remains
            for (int i = 0; i < data.Palette.IncludeColors.Count && palList.Count < maxPaletteSlots; i++)
            {
                palList.Add(data.Palette.IncludeColors[i]);
            }
        }
        else
        {
            // No transparency: start with computed palette and append include colors
            palList.AddRange(palette);
            for (int i = 0; i < data.Palette.IncludeColors.Count && palList.Count < maxPaletteSlots; i++)
            {
                palList.Add(data.Palette.IncludeColors[i]);
            }
        }

        palette = palList.ToArray();

        byte[] indexes;

        if (data.Input.Dithering)
        {
            indexes = Dither(
                pixels,
                data.Input.Resize.Width,
                data.Input.Resize.Height,
                palette,
                transparentMask,
                computedTransparentIndex);
        }
        else
        {
            indexes = MapToPalette(
                pixels,
                palette,
                transparentMask,
                computedTransparentIndex);
        }

        // Apply transparent index to masked pixels (override mapped indexes)
        if (hasTransparentColor && computedTransparentIndex >= 0)
        {
            for (int i = 0; i < pixels.Length; i++)
            {
                if (transparentMask[i])
                    indexes[i] = (byte)computedTransparentIndex;
            }
        }

        byte[] packedData = PackIndexes(
            indexes,
            data.Input.Resize.Width,
            data.Input.Resize.Height,
            data.Output.Palette);

        int finalTransparentIndex = (hasTransparentColor && computedTransparentIndex >= 0)
            ? computedTransparentIndex
            : -1;

        return new IndexedImage(
            data.Input.Resize.Width,
            data.Input.Resize.Height,
            data.Output.Palette,
            packedData,
            palette,
            finalTransparentIndex);
    }


    // ============================================================
    // COLOR COUNT
    // ============================================================

    private static int GetColorsCount(ColorDepth depth)
    {
        return depth switch
        {
            ColorDepth.Bpp1 => 2,
            ColorDepth.Bpp2 => 4,
            ColorDepth.Bpp4 => 16,
            ColorDepth.Bpp8 => 256,

            _ => throw new ArgumentOutOfRangeException(nameof(depth))
        };
    }


    // ============================================================
    // RESIZE
    // ============================================================

        private static Bitmap GetImage(DataModel input)
        {
        // Use 32bpp with alpha to preserve source transparency through crop/resize
        Bitmap result = new Bitmap(
            input.Input.Resize.Width,
            input.Input.Resize.Height,
            PixelFormat.Format32bppArgb);

        using Graphics g = Graphics.FromImage(result);
        g.CompositingMode = CompositingMode.SourceOver;
        // Start fully transparent
        g.Clear(Color.Transparent);

        if (input.Input.Bicubic)
        {
            g.InterpolationMode = InterpolationMode.Bicubic;
            g.PixelOffsetMode = PixelOffsetMode.HighQuality;
            g.SmoothingMode = SmoothingMode.HighQuality;
            g.CompositingQuality = CompositingQuality.HighQuality;
        } else
        {
            g.InterpolationMode = InterpolationMode.Low;
            g.PixelOffsetMode = PixelOffsetMode.None;
            g.SmoothingMode = SmoothingMode.None;
            g.CompositingQuality = CompositingQuality.AssumeLinear;
        }
        
        var p = input.Input.Crop; // Padding
        bool cropEnabled = (p.Left + p.Top + p.Right + p.Bottom) > 0;
        if (cropEnabled)
        {
            // compute source rect from padding
            int srcX = p.Left;
            int srcY = p.Top;
            int srcW = input.Image.Width - p.Left - p.Right;
            int srcH = input.Image.Height - p.Top - p.Bottom;

            if (srcX < 0) srcX = 0;
            if (srcY < 0) srcY = 0;
            if (srcW < 0) srcW = 0;
            if (srcH < 0) srcH = 0;

            if (srcW > 0 && srcH > 0 && srcX < input.Image.Width && srcY < input.Image.Height)
            {
                var srcRect = new Rectangle(srcX, srcY, srcW, srcH);

                g.DrawImage(
                    input.Image,
                    new Rectangle(0, 0, input.Input.Resize.Width, input.Input.Resize.Height),
                    srcRect,
                    GraphicsUnit.Pixel);
            }
            else
            {
                // nothing to draw when padding excludes entire image
            }
        }
        else
        {
                // Draw image preserving alpha
                g.DrawImage(
                input.Image,
                new Rectangle(0, 0, input.Input.Resize.Width, input.Input.Resize.Height));
        }
        

        input.Filters.Apply(result);

        return result;
    }


    // ============================================================
    // GET PIXELS
    // ============================================================

    private static Color[] GetPixels(Bitmap bitmap)
    {
        Color[] pixels = new Color[
            bitmap.Width * bitmap.Height];

        int index = 0;

        for (int y = 0; y < bitmap.Height; y++)
        {
            for (int x = 0; x < bitmap.Width; x++)
            {
                pixels[index++] = bitmap.GetPixel(x, y);
            }
        }

        return pixels;
    }


    // ============================================================
    // MEDIAN CUT
    // ============================================================

    private sealed class ColorBox
    {
        public List<Color> Colors { get; }

        public ColorBox(List<Color> colors)
        {
            Colors = colors;
        }

        public int RangeR
        {
            get
            {
                if (Colors.Count == 0)
                    return 0;

                int min = 255;
                int max = 0;

                foreach (Color c in Colors)
                {
                    min = Math.Min(min, c.R);
                    max = Math.Max(max, c.R);
                }

                return max - min;
            }
        }

        public int RangeG
        {
            get
            {
                if (Colors.Count == 0)
                    return 0;

                int min = 255;
                int max = 0;

                foreach (Color c in Colors)
                {
                    min = Math.Min(min, c.G);
                    max = Math.Max(max, c.G);
                }

                return max - min;
            }
        }

        public int RangeB
        {
            get
            {
                if (Colors.Count == 0)
                    return 0;

                int min = 255;
                int max = 0;

                foreach (Color c in Colors)
                {
                    min = Math.Min(min, c.B);
                    max = Math.Max(max, c.B);
                }

                return max - min;
            }
        }

        public int LargestRange
        {
            get
            {
                return Math.Max(
                    RangeR,
                    Math.Max(RangeG, RangeB));
            }
        }
    }


    private static Color[] BuildPalette(
        Color[] pixels,
        int colorCount)
    {
        var boxes = new List<ColorBox>
        {
            new ColorBox(new List<Color>(pixels))
        };

        while (boxes.Count < colorCount)
        {
            ColorBox? boxToSplit = null;

            int largestRange = -1;

            foreach (ColorBox box in boxes)
            {
                if (box.Colors.Count <= 1)
                    continue;

                if (box.LargestRange > largestRange)
                {
                    largestRange = box.LargestRange;
                    boxToSplit = box;
                }
            }

            if (boxToSplit == null)
                break;

            ColorBox[] split = SplitBox(boxToSplit);

            boxes.Remove(boxToSplit);
            boxes.Add(split[0]);
            boxes.Add(split[1]);
        }

        var palette = new List<Color>();

        foreach (ColorBox box in boxes)
        {
            if (box.Colors.Count == 0)
                continue;

            long r = 0;
            long g = 0;
            long b = 0;

            foreach (Color c in box.Colors)
            {
                r += c.R;
                g += c.G;
                b += c.B;
            }

            int count = box.Colors.Count;

            palette.Add(
                Color.FromArgb(
                    (int)(r / count),
                    (int)(g / count),
                    (int)(b / count)));
        }

        return palette.ToArray();
    }


    private static ColorBox[] SplitBox(ColorBox box)
    {
        int rangeR = box.RangeR;
        int rangeG = box.RangeG;
        int rangeB = box.RangeB;

        if (rangeR >= rangeG && rangeR >= rangeB)
        {
            box.Colors.Sort((a, b) =>
                a.R.CompareTo(b.R));
        }
        else if (rangeG >= rangeR && rangeG >= rangeB)
        {
            box.Colors.Sort((a, b) =>
                a.G.CompareTo(b.G));
        }
        else
        {
            box.Colors.Sort((a, b) =>
                a.B.CompareTo(b.B));
        }

        int middle = box.Colors.Count / 2;

        List<Color> left =
            box.Colors.GetRange(
                0,
                middle);

        List<Color> right =
            box.Colors.GetRange(
                middle,
                box.Colors.Count - middle);

        return new[]
        {
            new ColorBox(left),
            new ColorBox(right)
        };
    }


    // ============================================================
    // MAP COLORS
    // ============================================================

        private static byte[] MapToPalette(
        Color[] pixels,
        Color[] palette,
        bool[] transparentMask,
        int transparentIndex)
    {
        byte[] indexes = new byte[pixels.Length];

        for (int i = 0; i < pixels.Length; i++)
        {
            if (transparentMask != null && i < transparentMask.Length && transparentMask[i])
            {
                indexes[i] = (byte)(transparentIndex >= 0 ? transparentIndex : 0);
            }
            else
            {
                indexes[i] =
                    (byte)FindNearestColor(
                        pixels[i],
                        palette);
            }
        }

        return indexes;
    }


    // ============================================================
    // FLOYD-STEINBERG DITHERING
    // ============================================================

        private static byte[] Dither(
        Color[] pixels,
        int width,
        int height,
        Color[] palette,
        bool[] transparentMask,
        int transparentIndex)
    {
        byte[] indexes = new byte[pixels.Length];

        float[] r = new float[pixels.Length];
        float[] g = new float[pixels.Length];
        float[] b = new float[pixels.Length];

        for (int i = 0; i < pixels.Length; i++)
        {
            r[i] = pixels[i].R;
            g[i] = pixels[i].G;
            b[i] = pixels[i].B;
        }

        for (int y = 0; y < height; y++)
        {
            bool reverse = (y & 1) != 0;

            int startX = reverse ? width - 1 : 0;
            int endX = reverse ? -1 : width;
            int step = reverse ? -1 : 1;

            for (int x = startX; x != endX; x += step)
            {
                int pixelIndex =
                    y * width + x;

                // If this pixel is marked transparent, assign transparent index and skip error diffusion
                if (transparentMask != null && pixelIndex < transparentMask.Length && transparentMask[pixelIndex])
                {
                    indexes[pixelIndex] = (byte)(transparentIndex >= 0 ? transparentIndex : 0);
                    continue;
                }

                Color current = Color.FromArgb(
                    ClampToByte(r[pixelIndex]),
                    ClampToByte(g[pixelIndex]),
                    ClampToByte(b[pixelIndex]));

                int paletteIndex =
                    FindNearestColor(
                        current,
                        palette);

                indexes[pixelIndex] =
                    (byte)paletteIndex;

                Color replacement =
                    palette[paletteIndex];

                float errorR =
                    r[pixelIndex] - replacement.R;

                float errorG =
                    g[pixelIndex] - replacement.G;

                float errorB =
                    b[pixelIndex] - replacement.B;

                if (!reverse)
                {
                    AddError(
                        r, g, b,
                        width,
                        height,
                        x + 1, y,
                        errorR,
                        errorG,
                        errorB,
                        7f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x - 1, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        3f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        5f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x + 1, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        1f / 16f);
                }
                else
                {
                    AddError(
                        r, g, b,
                        width,
                        height,
                        x - 1, y,
                        errorR,
                        errorG,
                        errorB,
                        7f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x + 1, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        3f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        5f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x - 1, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        1f / 16f);
                }
            }
        }

        return indexes;
    }


    private static void AddError(
        float[] r,
        float[] g,
        float[] b,
        int width,
        int height,
        int x,
        int y,
        float errorR,
        float errorG,
        float errorB,
        float factor)
    {
        if (x < 0 ||
            x >= width ||
            y < 0 ||
            y >= height)
        {
            return;
        }

        int index =
            y * width + x;

        r[index] += errorR * factor;
        g[index] += errorG * factor;
        b[index] += errorB * factor;
    }


    // ============================================================
    // FIND NEAREST COLOR
    // ============================================================

    private static int FindNearestColor(
        Color color,
        Color[] palette)
    {
        int bestIndex = 0;
        int bestDistance = int.MaxValue;

        for (int i = 0; i < palette.Length; i++)
        {
            int dr = color.R - palette[i].R;
            int dg = color.G - palette[i].G;
            int db = color.B - palette[i].B;

            // Weighted distance roughly matching human
            // sensitivity to green.
            int distance =
                dr * dr * 30 +
                dg * dg * 59 +
                db * db * 11;

            if (distance < bestDistance)
            {
                bestDistance = distance;
                bestIndex = i;
            }
        }

        return bestIndex;
    }


    // ============================================================
    // PACK INDEXES
    // ============================================================

    private static byte[] PackIndexes(
        byte[] indexes,
        int width,
        int height,
        ColorDepth colorDepth)
    {
        int bitsPerPixel = (int)colorDepth;

        int pixelsPerByte =
            8 / bitsPerPixel;

        int dataSize =
            (indexes.Length + pixelsPerByte - 1)
            / pixelsPerByte;

        byte[] data =
            new byte[dataSize];

        int mask =
            (1 << bitsPerPixel) - 1;

        for (int i = 0; i < indexes.Length; i++)
        {
            int byteIndex =
                i / pixelsPerByte;

            int position =
                i % pixelsPerByte;

            int shift =
                8 - bitsPerPixel * (position + 1);

            data[byteIndex] |=
                (byte)((indexes[i] & mask) << shift);
        }

        return data;
    }


    // ============================================================
    // RGB888 -> RGB565
    // ============================================================

    private static ushort ToRgb565(Color color)
    {
        return (ushort)(
            ((color.R & 0xF8) << 8) |
            ((color.G & 0xFC) << 3) |
            (color.B >> 3));
    }


    // ============================================================
    // GENERATED getPixel()
    // ============================================================

    private static void AppendGetPixelFunction(
        StringBuilder sb,
        string identifier,
        string macroName,
        bool useColor565,
        bool hasTransparency)
    {
        sb.AppendLine(
            $"static inline uint16_t {identifier}GetPixel(");
        sb.AppendLine(
            "    uint16_t x,");
        sb.AppendLine(
            "    uint16_t y)");
        sb.AppendLine("{");

        sb.AppendLine(
            $"    if (x >= {macroName}_WIDTH || " +
            $"y >= {macroName}_HEIGHT)");
        sb.AppendLine(
            "        return 0;");
        sb.AppendLine();

        sb.AppendLine(
            "    uint32_t pixelIndex = " +
            $"(uint32_t)y * {macroName}_WIDTH + x;");
        sb.AppendLine();

        sb.AppendLine(
            "    uint8_t paletteIndex;");
        sb.AppendLine();

        // --------------------------------------------------------
        // 1 BPP
        // --------------------------------------------------------

        sb.AppendLine(
            $"    #if {macroName}_BPP == 1");

        sb.AppendLine(
            "    uint32_t byteIndex = pixelIndex >> 3;");

        sb.AppendLine(
            "    uint8_t shift = 7 - (pixelIndex & 7);");

        sb.AppendLine(
            $"    paletteIndex = " +
            $"(pgm_read_byte(&{identifier}[byteIndex]) >> shift) & 0x01;");

        // --------------------------------------------------------
        // 2 BPP
        // --------------------------------------------------------

        sb.AppendLine(
            $"    #elif {macroName}_BPP == 2");

        sb.AppendLine(
            "    uint32_t byteIndex = pixelIndex >> 2;");

        sb.AppendLine(
            "    uint8_t shift = 6 - ((pixelIndex & 3) * 2);");

        sb.AppendLine(
            $"    paletteIndex = " +
            $"(pgm_read_byte(&{identifier}[byteIndex]) >> shift) & 0x03;");

        // --------------------------------------------------------
        // 4 BPP
        // --------------------------------------------------------

        sb.AppendLine(
            $"    #elif {macroName}_BPP == 4");

        sb.AppendLine(
            "    uint32_t byteIndex = pixelIndex >> 1;");

        sb.AppendLine(
            "    uint8_t shift = " +
            "(pixelIndex & 1) ? 0 : 4;");

        sb.AppendLine(
            $"    paletteIndex = " +
            $"(pgm_read_byte(&{identifier}[byteIndex]) >> shift) & 0x0F;");

        // --------------------------------------------------------
        // 8 BPP
        // --------------------------------------------------------

        sb.AppendLine(
            $"    #else");

        sb.AppendLine(
            $"    paletteIndex = " +
            $"pgm_read_byte(&{identifier}[pixelIndex]);");

        sb.AppendLine(
            $"    #endif");

        sb.AppendLine();

        // --------------------------------------------------------
        // TRANSPARENCY CHECK
        // --------------------------------------------------------
        if (hasTransparency)
        {
            sb.AppendLine(
                $"    if (paletteIndex == {macroName}_TRANSPARENT_INDEX)");
            sb.AppendLine(
                "        return 0xFFFF;");
            sb.AppendLine();
        }

        // --------------------------------------------------------
        // RGB565 PALETTE
        // --------------------------------------------------------

        if (useColor565)
        {
            sb.AppendLine(
                $"    return pgm_read_word(" +
                $"&{identifier}Palette[paletteIndex]);");
        }
        else
        {
            sb.AppendLine(
                $"    uint8_t r = " +
                $"pgm_read_byte(&{identifier}Palette[paletteIndex][0]);");

            sb.AppendLine(
                $"    uint8_t g = " +
                $"pgm_read_byte(&{identifier}Palette[paletteIndex][1]);");

            sb.AppendLine(
                $"    uint8_t b = " +
                $"pgm_read_byte(&{identifier}Palette[paletteIndex][2]);");

            sb.AppendLine();

            sb.AppendLine(
                "    return (uint16_t)(");

            sb.AppendLine(
                "        ((r & 0xF8) << 8) |");

            sb.AppendLine(
                "        ((g & 0xFC) << 3) |");

            sb.AppendLine(
                "        (b >> 3));");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }


    // ============================================================
    // BYTE ARRAY OUTPUT
    // ============================================================

    private static void AppendByteArray(
        StringBuilder sb,
        byte[] data)
    {
        const int bytesPerLine = 16;

        for (int i = 0; i < data.Length; i++)
        {
            if (i % bytesPerLine == 0)
                sb.Append("    ");

            sb.Append($"0x{data[i]:X2}");

            if (i < data.Length - 1)
                sb.Append(", ");

            if ((i + 1) % bytesPerLine == 0)
                sb.AppendLine();
        }

        if (data.Length % bytesPerLine != 0)
            sb.AppendLine();
    }


    // ============================================================
    // IDENTIFIER
    // ============================================================

    private static string MakeIdentifier(string name)
    {
        var sb = new StringBuilder();

        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }

        if (sb.Length == 0)
            sb.Append("image");

        if (char.IsDigit(sb[0]))
            sb.Insert(0, '_');

        return sb.ToString();
    }


    // ============================================================
    // CLAMP
    // ============================================================

    private static int ClampToByte(float value)
    {
        if (value < 0)
            return 0;

        if (value > 255)
            return 255;

        return (int)Math.Round(value);
    }
}