using Image2Cpp.Models;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Drawing.Imaging.Effects;
using System.Text;

public static class ArduinoImageConverter
{
    // ============================================================
    // COLOR DEPTH
    // ============================================================

    public enum ColorDepth
    {
        Bpp1 = 1,   // 2 colors
        Bpp2 = 2,   // 4 colors
        Bpp4 = 4,   // 16 colors
        Bpp8 = 8    // 256 colors
    }


    // ============================================================
    // RESULT
    // ============================================================

    public sealed class IndexedImage
    {
        public int Width { get; }
        public int Height { get; }
        public ColorDepth ColorDepth { get; }

        // Packed pixel indexes
        public byte[] Data { get; }

        // RGB palette
        public Color[] Palette { get; }

        // Transparent palette index (-1 = none)
        public int TransparentIndex { get; }

        public int ColorsCount => Palette.Length;

        public int BitsPerPixel => (int)ColorDepth;

        public IndexedImage(
            int width,
            int height,
            ColorDepth colorDepth,
            byte[] data,
            Color[] palette,
            int transparentIndex = -1)
        {
            Width = width;
            Height = height;
            ColorDepth = colorDepth;
            Data = data;
            Palette = palette;
            TransparentIndex = transparentIndex;
        }


        // ========================================================
        // ARDUINO CODE GENERATION
        // ========================================================

        public string ToArduinoCode(DataModel data)
        {
            if (string.IsNullOrWhiteSpace(data.Output.Name))
                throw new ArgumentException("Name cannot be empty.", nameof(data.Output.Name));

            string identifier = MakeIdentifier(data.Output.Name);
            string macroName = identifier.ToUpperInvariant();

            var sb = new StringBuilder();

            sb.AppendLine("// ============================================================");
            sb.AppendLine($"// Generated by ArduinoImageConverter - {macroName}");
            sb.AppendLine("// ============================================================");
            sb.AppendLine();

            sb.AppendLine($"#define {macroName}_WIDTH       {Width}");
            sb.AppendLine($"#define {macroName}_HEIGHT      {Height}");
            sb.AppendLine($"#define {macroName}_BPP         {BitsPerPixel}");
            sb.AppendLine($"#define {macroName}_COLORS      {ColorsCount}");
            sb.AppendLine($"#define {macroName}_DATA_SIZE   {Data.Length}");
            sb.AppendLine();

            // ----------------------------------------------------
            // PIXEL DATA
            // ----------------------------------------------------

            sb.AppendLine($"const uint8_t {identifier}[] PROGMEM =");
            sb.AppendLine("{");

            AppendByteArray(sb, Data);

            sb.AppendLine("};");
            sb.AppendLine();

            // ----------------------------------------------------
            // PALETTE
            // ----------------------------------------------------

            if (data.Output.UseColor565)
            {
                sb.AppendLine(
                    $"const uint16_t {identifier}Palette[{ColorsCount}] PROGMEM =");
                sb.AppendLine("{");

                for (int i = 0; i < Palette.Length; i++)
                {
                    ushort rgb565 = ToRgb565(Palette[i]);

                    sb.Append($"    0x{rgb565:X4}");

                    if (i < Palette.Length - 1)
                        sb.Append(",");

                    sb.AppendLine();
                }

                sb.AppendLine("};");
            }
            else
            {
                sb.AppendLine(
                    $"const uint8_t {identifier}Palette[{ColorsCount}][3] PROGMEM =");
                sb.AppendLine("{");

                for (int i = 0; i < Palette.Length; i++)
                {
                    Color c = Palette[i];

                    sb.AppendLine(
                        $"    {{ {c.R}, {c.G}, {c.B} }}" +
                        (i < Palette.Length - 1 ? "," : ""));
                }

                sb.AppendLine("};");
            }

            sb.AppendLine();

            // ----------------------------------------------------
            // TRANSPARENCY
            // ----------------------------------------------------
            bool hasTransparency = TransparentIndex >= 0 && this.TransparentIndex < Palette.Length;
            if (hasTransparency)
            {
                sb.AppendLine($"#define {macroName}_TRANSPARENT_INDEX   {this.TransparentIndex}");
                sb.AppendLine();
            }

            // ----------------------------------------------------
            // GET PIXEL
            // ----------------------------------------------------

            if (data.Output.IncludeRenderFunction)
            {
                AppendGetPixelFunction(
                    sb,
                    identifier,
                    macroName,
                    data.Output.UseColor565,
                    hasTransparency);
            }

            return sb.ToString();
        }

        public Bitmap ToBitmap()
        {
            return ToBitmap(preview: false);
        }

        public Bitmap ToBitmap(bool preview = false)
        {
            // Create foreground image as 32bpp to preserve alpha for transparent pixels
            var fg = new Bitmap(Width, Height, PixelFormat.Format32bppArgb);

            int bitsPerPixel = BitsPerPixel;
            int pixelsPerByte = 8 / bitsPerPixel;
            int mask = (1 << bitsPerPixel) - 1;

            bool hasTransparency = TransparentIndex >= 0;

            for (int i = 0; i < Width * Height; i++)
            {
                int byteIndex = i / pixelsPerByte;
                int position = i % pixelsPerByte;

                int shift = 8 - bitsPerPixel * (position + 1);

                int paletteIndex = (Data[byteIndex] >> shift) & mask;

                Color color = Palette[paletteIndex];

                int x = i % Width;
                int y = i / Width;

                if (hasTransparency && paletteIndex == TransparentIndex)
                {
                    // Transparent pixel
                    fg.SetPixel(x, y, Color.FromArgb(0, color.R, color.G, color.B));
                }
                else
                {
                    fg.SetPixel(x, y, color);
                }
            }

            if (!preview)
            {
                return fg;
            }

            // Preview: composite onto checkerboard background and return 24bpp image
            var previewBmp = new Bitmap(Width, Height, PixelFormat.Format24bppRgb);

            using (Graphics g = Graphics.FromImage(previewBmp))
            {
                int cell = 8;
                Color c1 = Color.FromArgb(220, 220, 220);
                Color c2 = Color.FromArgb(180, 180, 180);

                for (int y = 0; y < previewBmp.Height; y += cell)
                {
                    for (int x = 0; x < previewBmp.Width; x += cell)
                    {
                        bool odd = ((x / cell) + (y / cell)) % 2 == 1;
                        using (Brush b = new SolidBrush(odd ? c1 : c2))
                        {
                            g.FillRectangle(b, x, y, cell, cell);
                        }
                    }
                }

                g.DrawImage(fg, 0, 0, Width, Height);
            }

            fg.Dispose();

            return previewBmp;
        }

    }


    // ============================================================
    // PUBLIC CONVERSION FUNCTION
    // ============================================================

    public static IndexedImage Convert(DataModel data)
    {
        if (data == null)
            throw new ArgumentNullException(nameof(data));
        if (data.Image == null)
            throw new ArgumentNullException(nameof(data.Image));

        if (data.Input.Resize.Width <= 0)
            throw new ArgumentOutOfRangeException(nameof(data.Input.Resize.Width));


        if (data.Input.Resize.Height <= 0)
            throw new ArgumentOutOfRangeException(nameof(data.Input.Resize.Height));

        int colorsCount = GetColorsCount(data.Output.Palette);

        using Bitmap resized = GetImage(data);    

        Color[] pixels = GetPixels(resized);

        Color[] palette;
        if (data.Palette.UseCustomPalette && data.Palette.Colors.Count >= 2)
        {
            palette = data.Palette.Colors.ToArray();
        }
        else
        {
            palette = BuildPalette(
            pixels,
            (int)Math.Min(colorsCount, data.Input.MaxColors));
        }
        

        byte[] indexes;

        if (data.Input.Dithering)
        {
            indexes = Dither(
                pixels,
                data.Input.Resize.Width,
                data.Input.Resize.Height,
                palette);
        }
        else
        {
            indexes = MapToPalette(
                pixels,
                palette);
        }

        byte[] packedData = PackIndexes(
            indexes,
            data.Input.Resize.Width,
            data.Input.Resize.Height,
            data.Output.Palette);

        return new IndexedImage(
            data.Input.Resize.Width,
            data.Input.Resize.Height,
            data.Output.Palette,
            packedData,
            palette,
            data.Output.TransparentIndex);
    }


    // ============================================================
    // COLOR COUNT
    // ============================================================

    private static int GetColorsCount(ColorDepth depth)
    {
        return depth switch
        {
            ColorDepth.Bpp1 => 2,
            ColorDepth.Bpp2 => 4,
            ColorDepth.Bpp4 => 16,
            ColorDepth.Bpp8 => 256,

            _ => throw new ArgumentOutOfRangeException(nameof(depth))
        };
    }


    // ============================================================
    // RESIZE
    // ============================================================

    private static Bitmap GetImage(DataModel input)
    {
        Bitmap result = new Bitmap(
            input.Input.Resize.Width,
            input.Input.Resize.Height,
            PixelFormat.Format24bppRgb);

        using Graphics g = Graphics.FromImage(result);

        if (input.Input.Bicubic)
        {
            g.InterpolationMode = InterpolationMode.Bicubic;
            g.PixelOffsetMode = PixelOffsetMode.HighQuality;
            g.SmoothingMode = SmoothingMode.HighQuality;
            g.CompositingQuality = CompositingQuality.HighQuality;
        } else
        {
            g.InterpolationMode = InterpolationMode.Low;
            g.PixelOffsetMode = PixelOffsetMode.None;
            g.SmoothingMode = SmoothingMode.None;
            g.CompositingQuality = CompositingQuality.AssumeLinear;
        }
        
        var p = input.Input.Crop; // Padding
        bool cropEnabled = (p.Left + p.Top + p.Right + p.Bottom) > 0;
        if (cropEnabled)
        {
            // compute source rect from padding
            int srcX = p.Left;
            int srcY = p.Top;
            int srcW = input.Image.Width - p.Left - p.Right;
            int srcH = input.Image.Height - p.Top - p.Bottom;

            if (srcX < 0) srcX = 0;
            if (srcY < 0) srcY = 0;
            if (srcW < 0) srcW = 0;
            if (srcH < 0) srcH = 0;

            if (srcW > 0 && srcH > 0 && srcX < input.Image.Width && srcY < input.Image.Height)
            {
                var srcRect = new Rectangle(srcX, srcY, srcW, srcH);

                g.DrawImage(
                    input.Image,
                    new Rectangle(0, 0, input.Input.Resize.Width, input.Input.Resize.Height),
                    srcRect,
                    GraphicsUnit.Pixel);
            }
            else
            {
                // nothing to draw when padding excludes entire image
            }
        }
        else
        {
            g.DrawImage(
                input.Image,
                new Rectangle(0, 0, input.Input.Resize.Width, input.Input.Resize.Height));
        }
        

        input.Filters.Apply(result);

        return result;
    }


    // ============================================================
    // GET PIXELS
    // ============================================================

    private static Color[] GetPixels(Bitmap bitmap)
    {
        Color[] pixels = new Color[
            bitmap.Width * bitmap.Height];

        int index = 0;

        for (int y = 0; y < bitmap.Height; y++)
        {
            for (int x = 0; x < bitmap.Width; x++)
            {
                pixels[index++] = bitmap.GetPixel(x, y);
            }
        }

        return pixels;
    }


    // ============================================================
    // MEDIAN CUT
    // ============================================================

    private sealed class ColorBox
    {
        public List<Color> Colors { get; }

        public ColorBox(List<Color> colors)
        {
            Colors = colors;
        }

        public int RangeR
        {
            get
            {
                if (Colors.Count == 0)
                    return 0;

                int min = 255;
                int max = 0;

                foreach (Color c in Colors)
                {
                    min = Math.Min(min, c.R);
                    max = Math.Max(max, c.R);
                }

                return max - min;
            }
        }

        public int RangeG
        {
            get
            {
                if (Colors.Count == 0)
                    return 0;

                int min = 255;
                int max = 0;

                foreach (Color c in Colors)
                {
                    min = Math.Min(min, c.G);
                    max = Math.Max(max, c.G);
                }

                return max - min;
            }
        }

        public int RangeB
        {
            get
            {
                if (Colors.Count == 0)
                    return 0;

                int min = 255;
                int max = 0;

                foreach (Color c in Colors)
                {
                    min = Math.Min(min, c.B);
                    max = Math.Max(max, c.B);
                }

                return max - min;
            }
        }

        public int LargestRange
        {
            get
            {
                return Math.Max(
                    RangeR,
                    Math.Max(RangeG, RangeB));
            }
        }
    }


    private static Color[] BuildPalette(
        Color[] pixels,
        int colorCount)
    {
        var boxes = new List<ColorBox>
        {
            new ColorBox(new List<Color>(pixels))
        };

        while (boxes.Count < colorCount)
        {
            ColorBox? boxToSplit = null;

            int largestRange = -1;

            foreach (ColorBox box in boxes)
            {
                if (box.Colors.Count <= 1)
                    continue;

                if (box.LargestRange > largestRange)
                {
                    largestRange = box.LargestRange;
                    boxToSplit = box;
                }
            }

            if (boxToSplit == null)
                break;

            ColorBox[] split = SplitBox(boxToSplit);

            boxes.Remove(boxToSplit);
            boxes.Add(split[0]);
            boxes.Add(split[1]);
        }

        var palette = new List<Color>();

        foreach (ColorBox box in boxes)
        {
            if (box.Colors.Count == 0)
                continue;

            long r = 0;
            long g = 0;
            long b = 0;

            foreach (Color c in box.Colors)
            {
                r += c.R;
                g += c.G;
                b += c.B;
            }

            int count = box.Colors.Count;

            palette.Add(
                Color.FromArgb(
                    (int)(r / count),
                    (int)(g / count),
                    (int)(b / count)));
        }

        return palette.ToArray();
    }


    private static ColorBox[] SplitBox(ColorBox box)
    {
        int rangeR = box.RangeR;
        int rangeG = box.RangeG;
        int rangeB = box.RangeB;

        if (rangeR >= rangeG && rangeR >= rangeB)
        {
            box.Colors.Sort((a, b) =>
                a.R.CompareTo(b.R));
        }
        else if (rangeG >= rangeR && rangeG >= rangeB)
        {
            box.Colors.Sort((a, b) =>
                a.G.CompareTo(b.G));
        }
        else
        {
            box.Colors.Sort((a, b) =>
                a.B.CompareTo(b.B));
        }

        int middle = box.Colors.Count / 2;

        List<Color> left =
            box.Colors.GetRange(
                0,
                middle);

        List<Color> right =
            box.Colors.GetRange(
                middle,
                box.Colors.Count - middle);

        return new[]
        {
            new ColorBox(left),
            new ColorBox(right)
        };
    }


    // ============================================================
    // MAP COLORS
    // ============================================================

    private static byte[] MapToPalette(
        Color[] pixels,
        Color[] palette)
    {
        byte[] indexes = new byte[pixels.Length];

        for (int i = 0; i < pixels.Length; i++)
        {
            indexes[i] =
                (byte)FindNearestColor(
                    pixels[i],
                    palette);
        }

        return indexes;
    }


    // ============================================================
    // FLOYD-STEINBERG DITHERING
    // ============================================================

    private static byte[] Dither(
        Color[] pixels,
        int width,
        int height,
        Color[] palette)
    {
        byte[] indexes = new byte[pixels.Length];

        float[] r = new float[pixels.Length];
        float[] g = new float[pixels.Length];
        float[] b = new float[pixels.Length];

        for (int i = 0; i < pixels.Length; i++)
        {
            r[i] = pixels[i].R;
            g[i] = pixels[i].G;
            b[i] = pixels[i].B;
        }

        for (int y = 0; y < height; y++)
        {
            bool reverse = (y & 1) != 0;

            int startX = reverse ? width - 1 : 0;
            int endX = reverse ? -1 : width;
            int step = reverse ? -1 : 1;

            for (int x = startX; x != endX; x += step)
            {
                int pixelIndex =
                    y * width + x;

                Color current = Color.FromArgb(
                    ClampToByte(r[pixelIndex]),
                    ClampToByte(g[pixelIndex]),
                    ClampToByte(b[pixelIndex]));

                int paletteIndex =
                    FindNearestColor(
                        current,
                        palette);

                indexes[pixelIndex] =
                    (byte)paletteIndex;

                Color replacement =
                    palette[paletteIndex];

                float errorR =
                    r[pixelIndex] - replacement.R;

                float errorG =
                    g[pixelIndex] - replacement.G;

                float errorB =
                    b[pixelIndex] - replacement.B;

                if (!reverse)
                {
                    AddError(
                        r, g, b,
                        width,
                        height,
                        x + 1, y,
                        errorR,
                        errorG,
                        errorB,
                        7f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x - 1, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        3f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        5f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x + 1, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        1f / 16f);
                }
                else
                {
                    AddError(
                        r, g, b,
                        width,
                        height,
                        x - 1, y,
                        errorR,
                        errorG,
                        errorB,
                        7f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x + 1, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        3f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        5f / 16f);

                    AddError(
                        r, g, b,
                        width,
                        height,
                        x - 1, y + 1,
                        errorR,
                        errorG,
                        errorB,
                        1f / 16f);
                }
            }
        }

        return indexes;
    }


    private static void AddError(
        float[] r,
        float[] g,
        float[] b,
        int width,
        int height,
        int x,
        int y,
        float errorR,
        float errorG,
        float errorB,
        float factor)
    {
        if (x < 0 ||
            x >= width ||
            y < 0 ||
            y >= height)
        {
            return;
        }

        int index =
            y * width + x;

        r[index] += errorR * factor;
        g[index] += errorG * factor;
        b[index] += errorB * factor;
    }


    // ============================================================
    // FIND NEAREST COLOR
    // ============================================================

    private static int FindNearestColor(
        Color color,
        Color[] palette)
    {
        int bestIndex = 0;
        int bestDistance = int.MaxValue;

        for (int i = 0; i < palette.Length; i++)
        {
            int dr = color.R - palette[i].R;
            int dg = color.G - palette[i].G;
            int db = color.B - palette[i].B;

            // Weighted distance roughly matching human
            // sensitivity to green.
            int distance =
                dr * dr * 30 +
                dg * dg * 59 +
                db * db * 11;

            if (distance < bestDistance)
            {
                bestDistance = distance;
                bestIndex = i;
            }
        }

        return bestIndex;
    }


    // ============================================================
    // PACK INDEXES
    // ============================================================

    private static byte[] PackIndexes(
        byte[] indexes,
        int width,
        int height,
        ColorDepth colorDepth)
    {
        int bitsPerPixel = (int)colorDepth;

        int pixelsPerByte =
            8 / bitsPerPixel;

        int dataSize =
            (indexes.Length + pixelsPerByte - 1)
            / pixelsPerByte;

        byte[] data =
            new byte[dataSize];

        int mask =
            (1 << bitsPerPixel) - 1;

        for (int i = 0; i < indexes.Length; i++)
        {
            int byteIndex =
                i / pixelsPerByte;

            int position =
                i % pixelsPerByte;

            int shift =
                8 - bitsPerPixel * (position + 1);

            data[byteIndex] |=
                (byte)((indexes[i] & mask) << shift);
        }

        return data;
    }


    // ============================================================
    // RGB888 -> RGB565
    // ============================================================

    private static ushort ToRgb565(Color color)
    {
        return (ushort)(
            ((color.R & 0xF8) << 8) |
            ((color.G & 0xFC) << 3) |
            (color.B >> 3));
    }


    // ============================================================
    // GENERATED getPixel()
    // ============================================================

    private static void AppendGetPixelFunction(
        StringBuilder sb,
        string identifier,
        string macroName,
        bool useColor565,
        bool hasTransparency)
    {
        sb.AppendLine(
            $"static inline uint16_t {identifier}GetPixel(");
        sb.AppendLine(
            "    uint16_t x,");
        sb.AppendLine(
            "    uint16_t y)");
        sb.AppendLine("{");

        sb.AppendLine(
            $"    if (x >= {macroName}_WIDTH || " +
            $"y >= {macroName}_HEIGHT)");
        sb.AppendLine(
            "        return 0;");
        sb.AppendLine();

        sb.AppendLine(
            "    uint32_t pixelIndex = " +
            $"(uint32_t)y * {macroName}_WIDTH + x;");
        sb.AppendLine();

        sb.AppendLine(
            "    uint8_t paletteIndex;");
        sb.AppendLine();

        // --------------------------------------------------------
        // 1 BPP
        // --------------------------------------------------------

        sb.AppendLine(
            $"    #if {macroName}_BPP == 1");

        sb.AppendLine(
            "    uint32_t byteIndex = pixelIndex >> 3;");

        sb.AppendLine(
            "    uint8_t shift = 7 - (pixelIndex & 7);");

        sb.AppendLine(
            $"    paletteIndex = " +
            $"(pgm_read_byte(&{identifier}[byteIndex]) >> shift) & 0x01;");

        // --------------------------------------------------------
        // 2 BPP
        // --------------------------------------------------------

        sb.AppendLine(
            $"    #elif {macroName}_BPP == 2");

        sb.AppendLine(
            "    uint32_t byteIndex = pixelIndex >> 2;");

        sb.AppendLine(
            "    uint8_t shift = 6 - ((pixelIndex & 3) * 2);");

        sb.AppendLine(
            $"    paletteIndex = " +
            $"(pgm_read_byte(&{identifier}[byteIndex]) >> shift) & 0x03;");

        // --------------------------------------------------------
        // 4 BPP
        // --------------------------------------------------------

        sb.AppendLine(
            $"    #elif {macroName}_BPP == 4");

        sb.AppendLine(
            "    uint32_t byteIndex = pixelIndex >> 1;");

        sb.AppendLine(
            "    uint8_t shift = " +
            "(pixelIndex & 1) ? 0 : 4;");

        sb.AppendLine(
            $"    paletteIndex = " +
            $"(pgm_read_byte(&{identifier}[byteIndex]) >> shift) & 0x0F;");

        // --------------------------------------------------------
        // 8 BPP
        // --------------------------------------------------------

        sb.AppendLine(
            $"    #else");

        sb.AppendLine(
            $"    paletteIndex = " +
            $"pgm_read_byte(&{identifier}[pixelIndex]);");

        sb.AppendLine(
            $"    #endif");

        sb.AppendLine();

        // --------------------------------------------------------
        // TRANSPARENCY CHECK
        // --------------------------------------------------------
        if (hasTransparency)
        {
            sb.AppendLine(
                $"    if (paletteIndex == {macroName}_TRANSPARENT_INDEX)");
            sb.AppendLine(
                "        return 0xFFFF;");
            sb.AppendLine();
        }

        // --------------------------------------------------------
        // RGB565 PALETTE
        // --------------------------------------------------------

        if (useColor565)
        {
            sb.AppendLine(
                $"    return pgm_read_word(" +
                $"&{identifier}Palette[paletteIndex]);");
        }
        else
        {
            sb.AppendLine(
                $"    uint8_t r = " +
                $"pgm_read_byte(&{identifier}Palette[paletteIndex][0]);");

            sb.AppendLine(
                $"    uint8_t g = " +
                $"pgm_read_byte(&{identifier}Palette[paletteIndex][1]);");

            sb.AppendLine(
                $"    uint8_t b = " +
                $"pgm_read_byte(&{identifier}Palette[paletteIndex][2]);");

            sb.AppendLine();

            sb.AppendLine(
                "    return (uint16_t)(");

            sb.AppendLine(
                "        ((r & 0xF8) << 8) |");

            sb.AppendLine(
                "        ((g & 0xFC) << 3) |");

            sb.AppendLine(
                "        (b >> 3));");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }


    // ============================================================
    // BYTE ARRAY OUTPUT
    // ============================================================

    private static void AppendByteArray(
        StringBuilder sb,
        byte[] data)
    {
        const int bytesPerLine = 16;

        for (int i = 0; i < data.Length; i++)
        {
            if (i % bytesPerLine == 0)
                sb.Append("    ");

            sb.Append($"0x{data[i]:X2}");

            if (i < data.Length - 1)
                sb.Append(", ");

            if ((i + 1) % bytesPerLine == 0)
                sb.AppendLine();
        }

        if (data.Length % bytesPerLine != 0)
            sb.AppendLine();
    }


    // ============================================================
    // IDENTIFIER
    // ============================================================

    private static string MakeIdentifier(string name)
    {
        var sb = new StringBuilder();

        foreach (char c in name)
        {
            if (char.IsLetterOrDigit(c) || c == '_')
                sb.Append(c);
            else
                sb.Append('_');
        }

        if (sb.Length == 0)
            sb.Append("image");

        if (char.IsDigit(sb[0]))
            sb.Insert(0, '_');

        return sb.ToString();
    }


    // ============================================================
    // CLAMP
    // ============================================================

    private static int ClampToByte(float value)
    {
        if (value < 0)
            return 0;

        if (value > 255)
            return 255;

        return (int)Math.Round(value);
    }
}